# my-tyk-apis/my-first-api/openapi.yaml
openapi: 3.0.0
info:
  title: My First Tyk API
  version: 1.0.0
  description: An example API managed by Tyk and documented in Backstage.
servers:
  - url: https://your-tyk-gateway-domain/my-first-api/
    description: Tyk Gateway Production Server
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from Tyk!
